name       : tpm2-tss
version    : 4.0.1
release    : 6
source     :
    - https://github.com/tpm2-software/tpm2-tss/releases/download/4.0.1/tpm2-tss-4.0.1.tar.gz : 532a70133910b6bd842289915b3f9423c0205c0ea009d65294ca18a74087c950
license    : BSD-2-Clause
component  : system.base
summary    : OSS implementation of the TCG TPM2 Software Stack (TSS2)
description: |
    OSS implementation of the Trusted Computing Group's (TCG) TPM2 Software Stack (TSS).
builddeps  :
    - pkgconfig(json-c)
    - pkgconfig(libcurl)
    - pkgconfig(libtpms)
    - autoconf-archive
    - doxygen
    - valgrind
    # Tests
    - pkgconfig(uthash)
    - cmocka-devel
    - swtpm
setup      : |
    cp $pkgfiles/tss2-tcti-libtpms.map lib
    %patch -p1 -i $pkgfiles/218c0da8.patch
    %configure --disable-static \
               --sysconfdir=/usr/share/defaults/etc \
               --with-runstatedir=/run \
               --with-tmpfilesdir=%libdir%/tmpfiles.d \
               --with-sysusersdir=%libdir%/sysusers.d \
               --with-udevrulesprefix=60- \
               --enable-unit \
               --enable-integration \
               --enable-valgrind \
               --enable-self-generated-certificate
build      : |
    %make
install    : |
    %make_install

    # Created by tmpfiles
    rmdir $installdir/var/lib/tpm2-tss/system/keystore
    rmdir $installdir/var/lib/tpm2-tss/system/
    rmdir $installdir/var/lib/tpm2-tss/
    rmdir $installdir/var/lib/
    rmdir $installdir/var
    rmdir $installdir/run/tpm2-tss/eventlog
    rmdir $installdir/run/tpm2-tss/
    rmdir $installdir/run/
check      : |
    unset LD_PRELOAD
    make check
