name       : tpm2-tss
version    : 3.2.0
release    : 2
source     :
    - https://github.com/tpm2-software/tpm2-tss/releases/download/3.2.0/tpm2-tss-3.2.0.tar.gz : 48305e4144dcf6d10f3b25b7bccf0189fd2d1186feafd8cd68c6b17ecf0d7912
license    : BSD-2-Clause
component  : security.library
summary    : OSS implementation of the TCG TPM2 Software Stack (TSS2)
description: |
    OSS implementation of the Trusted Computing Group's (TCG) TPM2 Software Stack (TSS).
builddeps  :
    - pkgconfig(json-c)
    - pkgconfig(libcurl)
    - autoconf-archive
setup      : |
    %configure --disable-static \
               --with-tmpfilesdir=%libdir%/tmpfiles.d \
               --with-sysusersdir=%libdir%/sysusers.d \
               --with-udevrulesprefix=60-
build      : |
    %make
install    : |
    %make_install
